use std::fs;
use std::path::Path;

fn main() {
    let brushes_dir = Path::new("../../brushes");
    println!("cargo:rerun-if-changed={}", brushes_dir.display());

    let out_dir = std::env::var("OUT_DIR").unwrap();
    let dest = Path::new(&out_dir).join("builtin_brushes.rs");

    let mut includes = String::new();
    let mut match_arms = String::new();
    let mut list_entries = String::new();

    let abs_brushes = fs::canonicalize(brushes_dir).unwrap_or_else(|_| brushes_dir.to_path_buf());
    if let Ok(entries) = fs::read_dir(&abs_brushes) {
        let mut names: Vec<(String, String)> = Vec::new();
        for entry in entries.flatten() {
            let path = entry.path();
            if path.extension().map_or(false, |e| e == "png") {
                let stem = path.file_stem().unwrap().to_string_lossy().to_string();
                let const_name = format!(
                    "BRUSH_{}",
                    stem.to_uppercase().replace('-', "_").replace(' ', "_")
                );
                let abs_path = fs::canonicalize(&path).unwrap();
                let abs_str = abs_path.display().to_string().replace('\\', "/");
                names.push((stem, const_name.clone()));
                includes.push_str(&format!(
                    "const {const_name}: &[u8] = include_bytes!(\"{abs_str}\");\n"
                ));
                println!("cargo:rerun-if-changed={}", abs_path.display());
            }
        }
        names.sort_by(|a, b| a.0.cmp(&b.0));
        for (stem, const_name) in &names {
            match_arms.push_str(&format!(
                "        \"{stem}\" => Some({const_name}.to_vec()),\n"
            ));
            list_entries.push_str(&format!("    names.push_str(\"{stem},\");\n"));
        }
    }

    let code = format!(
        r##"// Auto-generated by build.rs — do not edit
{includes}
pub fn get_builtin_brush_tip_generated(name: &str) -> Option<Vec<u8>> {{
    match name {{
{match_arms}        _ => None,
    }}
}}

pub fn list_builtin_brush_tips() -> String {{
    let mut names = String::new();
{list_entries}    names
}}
"##
    );

    fs::write(dest, code).unwrap();
}
