import type { Color, FontStyle, TextAlign } from '../types';
import type { GradientStop, GradientType } from '../tools/gradient/gradient';
import type { ShapeMode, ShapeOutput } from '../tools/shape/shape';
import type { SpongeMode } from '../tools/sponge/sponge';
import type { BrushPreset, BrushTipData, BrushTextureData, BrushTextureBlendMode, SubBrush } from '../types/brush';
import type { WandSettings } from '../tools/wand/wand-settings';
import type { FillSettings } from '../tools/fill/fill-settings';
import type { MarqueeSettings } from '../tools/marquee/marquee-settings';
import type { DodgeSettings } from '../tools/dodge/dodge-settings';
import type { ToolSettingsSlices } from './tool-settings-slices';

export interface ToolSettings {
  /**
   * Per-tool settings, keyed by tool. Each tool's slice is the
   * authoritative source of its settings — read via
   * `settings.<tool>.<field>` and write via `setWandSetting`-style
   * typed setters. Replaces the legacy flat-bag `<tool><Field>`
   * naming (see #453). Tools migrate one at a time; while the rollout
   * is in progress, untouched tools still expose their fields flat
   * on this interface.
   */
  settings: ToolSettingsSlices;
  brushSize: number;
  brushOpacity: number;
  brushHardness: number;
  pencilSize: number;
  eraserSize: number;
  eraserOpacity: number;
  shapeMode: ShapeMode;
  shapeOutput: ShapeOutput;
  shapeFillColor: Color | null;
  shapeStrokeColor: Color | null;
  shapeStrokeWidth: number;
  shapePolygonSides: number;
  shapeCornerRadius: number;
  aspectRatioW: number;
  aspectRatioH: number;
  aspectRatioLocked: boolean;
  cropMode: 'normal' | 'perspective';
  gradientType: GradientType;
  gradientStops: readonly GradientStop[];
  gradientReverse: boolean;
  stampSize: number;
  healingSize: number;
  healingOpacity: number;
  pathStrokeWidth: number;
  spongeMode: SpongeMode;
  spongeStrength: number;
  spongeSize: number;
  smudgeSize: number;
  smudgeStrength: number;
  quickSelectSize: number;
  quickSelectTolerance: number;
  quickSelectEdgeStrength: number;
  quickSelectMode: 'add' | 'subtract';
  magneticLassoWidth: number;
  magneticLassoContrast: number;
  magneticLassoFrequency: number;
  textContent: string;
  textFontSize: number;
  textFontFamily: string;
  textFontWeight: number;
  textFontStyle: FontStyle;
  textAlign: TextAlign;
  textUnderline: boolean;
  textStrikethrough: boolean;
  brushSpacing: number;
  brushScatter: number;
  brushAngle: number;
  brushFade: number;
  brushTaper: number;
  activeBrushTip: BrushTipData | null;
  symmetryHorizontal: boolean;
  symmetryVertical: boolean;
  symmetryRadialSegments: number;
  symmetryCenter: { x: number; y: number } | null;
  foregroundColor: Color;
  backgroundColor: Color;
  recentColors: readonly Color[];
  spraySize: number;
  sprayDensity: number;
  sprayOpacity: number;
  sprayHardness: number;
  brushSizeJitter: number;
  brushAngleJitter: number;
  brushOpacityJitter: number;
  brushHardnessJitter: number;
  brushSpeedSize: number;
  brushSpeedSizeInvert: boolean;
  brushSpeedSensitivity: 'low' | 'med' | 'high';
  brushTextureData: BrushTextureData | null;
  brushTextureBlendMode: BrushTextureBlendMode;
  brushTextureScale: number;
  brushTextures: BrushTextureData[];
  presets: BrushPreset[];
  activePresetId: string | null;
  activeSubBrushes: SubBrush[];

  setBrushSizeJitter: (jitter: number) => void;
  setBrushAngleJitter: (jitter: number) => void;
  setBrushOpacityJitter: (jitter: number) => void;
  setBrushHardnessJitter: (jitter: number) => void;
  setBrushSpeedSize: (value: number) => void;
  setBrushSpeedSizeInvert: (invert: boolean) => void;
  setBrushSpeedSensitivity: (sensitivity: 'low' | 'med' | 'high') => void;
  setBrushTextureData: (texture: BrushTextureData | null) => void;
  setBrushTextureBlendMode: (mode: BrushTextureBlendMode) => void;
  setBrushTextureScale: (scale: number) => void;
  addBrushTexture: (texture: BrushTextureData) => void;
  removeBrushTexture: (id: string) => void;
  setSpraySize: (size: number) => void;
  setSprayDensity: (density: number) => void;
  setSprayOpacity: (opacity: number) => void;
  setSprayHardness: (hardness: number) => void;
  setBrushSize: (size: number) => void;
  setBrushFade: (fade: number) => void;
  setBrushTaper: (taper: number) => void;
  setBrushSpacing: (spacing: number) => void;
  setBrushScatter: (scatter: number) => void;
  setBrushAngle: (angle: number) => void;
  setActiveBrushTip: (tip: BrushTipData | null) => void;
  setStampSize: (size: number) => void;
  setHealingSize: (size: number) => void;
  setHealingOpacity: (opacity: number) => void;
  setPathStrokeWidth: (width: number) => void;
  setDodgeSetting: <K extends keyof DodgeSettings>(key: K, value: DodgeSettings[K]) => void;
  setSpongeMode: (mode: SpongeMode) => void;
  setSpongeStrength: (strength: number) => void;
  setSpongeSize: (size: number) => void;
  setSmudgeSize: (size: number) => void;
  setSmudgeStrength: (strength: number) => void;
  setMarqueeSetting: <K extends keyof MarqueeSettings>(key: K, value: MarqueeSettings[K]) => void;
  setWandSetting: <K extends keyof WandSettings>(key: K, value: WandSettings[K]) => void;
  setQuickSelectSize: (size: number) => void;
  setQuickSelectTolerance: (tolerance: number) => void;
  setQuickSelectEdgeStrength: (strength: number) => void;
  setQuickSelectMode: (mode: 'add' | 'subtract') => void;
  setMagneticLassoWidth: (width: number) => void;
  setMagneticLassoContrast: (contrast: number) => void;
  setMagneticLassoFrequency: (frequency: number) => void;
  setTextContent: (content: string) => void;
  setTextFontSize: (size: number) => void;
  setTextFontFamily: (family: string) => void;
  setTextFontWeight: (weight: number) => void;
  setTextFontStyle: (style: FontStyle) => void;
  setTextAlign: (align: TextAlign) => void;
  setTextUnderline: (underline: boolean) => void;
  setTextStrikethrough: (strikethrough: boolean) => void;
  setBrushOpacity: (opacity: number) => void;
  setBrushHardness: (hardness: number) => void;
  setPencilSize: (size: number) => void;
  setEraserSize: (size: number) => void;
  setEraserOpacity: (opacity: number) => void;
  setFillSetting: <K extends keyof FillSettings>(key: K, value: FillSettings[K]) => void;
  setShapeMode: (mode: ShapeMode) => void;
  setShapeOutput: (output: ShapeOutput) => void;
  setShapeFillColor: (color: Color | null) => void;
  setShapeStrokeColor: (color: Color | null) => void;
  setShapeStrokeWidth: (width: number) => void;
  setShapePolygonSides: (sides: number) => void;
  setShapeCornerRadius: (radius: number) => void;
  setAspectRatioW: (w: number) => void;
  setAspectRatioH: (h: number) => void;
  setAspectRatioLocked: (locked: boolean) => void;
  setCropMode: (mode: 'normal' | 'perspective') => void;
  setGradientType: (type: 'linear' | 'radial') => void;
  setGradientStops: (stops: readonly GradientStop[]) => void;
  setGradientReverse: (reverse: boolean) => void;
  addGradientStop: (position: number, color: Color) => void;
  removeGradientStop: (index: number) => void;
  updateGradientStop: (index: number, stop: Partial<GradientStop>) => void;
  setSymmetryHorizontal: (enabled: boolean) => void;
  setSymmetryVertical: (enabled: boolean) => void;
  setSymmetryRadialSegments: (segments: number) => void;
  setSymmetryCenter: (center: { x: number; y: number } | null) => void;
  setForegroundColor: (color: Color) => void;
  setBackgroundColor: (color: Color) => void;
  swapColors: () => void;
  resetColors: () => void;
  addRecentColor: (color: Color) => void;
  addSubBrush: (sub: SubBrush) => void;
  removeSubBrush: (index: number) => void;
  updateSubBrush: (index: number, patch: Partial<SubBrush>) => void;
  clearSubBrushes: () => void;
  addPreset: (preset: BrushPreset) => void;
  addPresets: (presets: BrushPreset[]) => void;
  saveCurrentAsPreset: (name: string) => void;
  removePreset: (id: string) => void;
  updatePreset: (id: string, patch: Partial<Omit<BrushPreset, 'id'>>) => void;
  setActivePreset: (id: string) => void;
  setTipFromPreset: (id: string) => void;
}
